/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  DirectoryAssertionV3AssertionsListParams,
  DirectoryModelV3ManifestDeleteParams,
  DirectoryReaderV3GraphParams,
  DirectoryReaderV3ObjectGetParams,
  DirectoryReaderV3ObjectsListParams,
  DirectoryReaderV3RelationGetParams,
  DirectoryReaderV3RelationsListParams,
  DirectoryWriterV3ObjectDeleteParams,
  DirectoryWriterV3RelationDeleteParams,
  RpcStatus,
  V3CheckPermissionRequest,
  V3CheckPermissionResponse,
  V3CheckRelationRequest,
  V3CheckRelationResponse,
  V3CheckRequest,
  V3CheckResponse,
  V3ChecksRequest,
  V3ChecksResponse,
  V3DeleteAssertionResponse,
  V3DeleteManifestResponse,
  V3DeleteObjectResponse,
  V3DeleteRelationResponse,
  V3GetAssertionResponse,
  V3GetGraphResponse,
  V3GetObjectResponse,
  V3GetObjectsResponse,
  V3GetRelationResponse,
  V3GetRelationsResponse,
  V3ListAssertionsResponse,
  V3SetAssertionRequest,
  V3SetAssertionResponse,
  V3SetManifestResponse,
  V3SetObjectRequest,
  V3SetObjectResponse,
  V3SetRelationRequest,
  V3SetRelationResponse
} from '../../types/directory';

import { useDirectoryReaderClient } from '../clients/rest';
import { useDirectoryModelClient } from '../clients/rest';
import { useDirectoryWriterClient } from '../clients/rest';
/**
 * Set assertion.
 * @summary Set assertion
 */
export const useDirectoryAssertionV3AssertionSetHook = () => {
        const directoryAssertionV3AssertionSet = useDirectoryReaderClient<V3SetAssertionResponse>();

        return useCallback((
    v3SetAssertionRequest: V3SetAssertionRequest,
 signal?: AbortSignal
) => {
        return directoryAssertionV3AssertionSet(
          {url: `/api/v3/directory/assertion`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: v3SetAssertionRequest, signal
    },
          );
        }, [directoryAssertionV3AssertionSet])
      }
    


export const useDirectoryAssertionV3AssertionSetMutationOptions = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionSetHook>>>, TError,{data: V3SetAssertionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionSetHook>>>, TError,{data: V3SetAssertionRequest}, TContext> => {
    
const mutationKey = ['directoryAssertionV3AssertionSet'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const directoryAssertionV3AssertionSet =  useDirectoryAssertionV3AssertionSetHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionSetHook>>>, {data: V3SetAssertionRequest}> = (props) => {
          const {data} = props ?? {};

          return  directoryAssertionV3AssertionSet(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DirectoryAssertionV3AssertionSetMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionSetHook>>>>
    export type DirectoryAssertionV3AssertionSetMutationBody = V3SetAssertionRequest
    export type DirectoryAssertionV3AssertionSetMutationError = RpcStatus

    /**
 * @summary Set assertion
 */
export const useDirectoryAssertionV3AssertionSet = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionSetHook>>>, TError,{data: V3SetAssertionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionSetHook>>>,
        TError,
        {data: V3SetAssertionRequest},
        TContext
      > => {

      const mutationOptions = useDirectoryAssertionV3AssertionSetMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Delete assertion.
 * @summary Delete assertion
 */
export const useDirectoryAssertionV3AssertionDeleteHook = () => {
        const directoryAssertionV3AssertionDelete = useDirectoryReaderClient<V3DeleteAssertionResponse>();

        return useCallback((
    id: number,
 ) => {
        return directoryAssertionV3AssertionDelete(
          {url: `/api/v3/directory/assertion/${id}`, method: 'DELETE'
    },
          );
        }, [directoryAssertionV3AssertionDelete])
      }
    


export const useDirectoryAssertionV3AssertionDeleteMutationOptions = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionDeleteHook>>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionDeleteHook>>>, TError,{id: number}, TContext> => {
    
const mutationKey = ['directoryAssertionV3AssertionDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const directoryAssertionV3AssertionDelete =  useDirectoryAssertionV3AssertionDeleteHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionDeleteHook>>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  directoryAssertionV3AssertionDelete(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DirectoryAssertionV3AssertionDeleteMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionDeleteHook>>>>
    
    export type DirectoryAssertionV3AssertionDeleteMutationError = RpcStatus

    /**
 * @summary Delete assertion
 */
export const useDirectoryAssertionV3AssertionDelete = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionDeleteHook>>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionDeleteHook>>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = useDirectoryAssertionV3AssertionDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Returns single assertion instance.
 * @summary Get assertion instance
 */
export const useDirectoryAssertionV3AssertionGetHook = () => {
        const directoryAssertionV3AssertionGet = useDirectoryReaderClient<V3GetAssertionResponse>();

        return useCallback((
    id: number,
 signal?: AbortSignal
) => {
        return directoryAssertionV3AssertionGet(
          {url: `/api/v3/directory/assertion/${id}`, method: 'GET', signal
    },
          );
        }, [directoryAssertionV3AssertionGet])
      }
    

export const getDirectoryAssertionV3AssertionGetQueryKey = (id: number,) => {
    return [`/api/v3/directory/assertion/${id}`] as const;
    }

    
export const useDirectoryAssertionV3AssertionGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>, TError = RpcStatus>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDirectoryAssertionV3AssertionGetQueryKey(id);

  const directoryAssertionV3AssertionGet =  useDirectoryAssertionV3AssertionGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>> = ({ signal }) => directoryAssertionV3AssertionGet(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DirectoryAssertionV3AssertionGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>>
export type DirectoryAssertionV3AssertionGetQueryError = RpcStatus


export function useDirectoryAssertionV3AssertionGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>, TError = RpcStatus>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryAssertionV3AssertionGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>, TError = RpcStatus>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryAssertionV3AssertionGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>, TError = RpcStatus>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get assertion instance
 */

export function useDirectoryAssertionV3AssertionGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>, TError = RpcStatus>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useDirectoryAssertionV3AssertionGetQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns list of assertion instances.
 * @summary List assertions
 */
export const useDirectoryAssertionV3AssertionsListHook = () => {
        const directoryAssertionV3AssertionsList = useDirectoryReaderClient<V3ListAssertionsResponse>();

        return useCallback((
    params?: DirectoryAssertionV3AssertionsListParams,
 signal?: AbortSignal
) => {
        return directoryAssertionV3AssertionsList(
          {url: `/api/v3/directory/assertions`, method: 'GET',
        params, signal
    },
          );
        }, [directoryAssertionV3AssertionsList])
      }
    

export const getDirectoryAssertionV3AssertionsListQueryKey = (params?: DirectoryAssertionV3AssertionsListParams,) => {
    return [`/api/v3/directory/assertions`, ...(params ? [params]: [])] as const;
    }

    
export const useDirectoryAssertionV3AssertionsListInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, DirectoryAssertionV3AssertionsListParams['page.token']>, TError = RpcStatus>(params?: DirectoryAssertionV3AssertionsListParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, QueryKey, DirectoryAssertionV3AssertionsListParams['page.token']>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDirectoryAssertionV3AssertionsListQueryKey(params);

  const directoryAssertionV3AssertionsList =  useDirectoryAssertionV3AssertionsListHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, QueryKey, DirectoryAssertionV3AssertionsListParams['page.token']> = ({ signal, pageParam }) => directoryAssertionV3AssertionsList({...params, 'page.token': pageParam || params?.['page.token']}, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, QueryKey, DirectoryAssertionV3AssertionsListParams['page.token']> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DirectoryAssertionV3AssertionsListInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>>
export type DirectoryAssertionV3AssertionsListInfiniteQueryError = RpcStatus


export function useDirectoryAssertionV3AssertionsListInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, DirectoryAssertionV3AssertionsListParams['page.token']>, TError = RpcStatus>(
 params: undefined |  DirectoryAssertionV3AssertionsListParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, QueryKey, DirectoryAssertionV3AssertionsListParams['page.token']>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, QueryKey
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryAssertionV3AssertionsListInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, DirectoryAssertionV3AssertionsListParams['page.token']>, TError = RpcStatus>(
 params?: DirectoryAssertionV3AssertionsListParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, QueryKey, DirectoryAssertionV3AssertionsListParams['page.token']>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, QueryKey
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryAssertionV3AssertionsListInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, DirectoryAssertionV3AssertionsListParams['page.token']>, TError = RpcStatus>(
 params?: DirectoryAssertionV3AssertionsListParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, QueryKey, DirectoryAssertionV3AssertionsListParams['page.token']>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List assertions
 */

export function useDirectoryAssertionV3AssertionsListInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, DirectoryAssertionV3AssertionsListParams['page.token']>, TError = RpcStatus>(
 params?: DirectoryAssertionV3AssertionsListParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, QueryKey, DirectoryAssertionV3AssertionsListParams['page.token']>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useDirectoryAssertionV3AssertionsListInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions , queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const useDirectoryAssertionV3AssertionsListQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError = RpcStatus>(params?: DirectoryAssertionV3AssertionsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDirectoryAssertionV3AssertionsListQueryKey(params);

  const directoryAssertionV3AssertionsList =  useDirectoryAssertionV3AssertionsListHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>> = ({ signal }) => directoryAssertionV3AssertionsList(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DirectoryAssertionV3AssertionsListQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>>
export type DirectoryAssertionV3AssertionsListQueryError = RpcStatus


export function useDirectoryAssertionV3AssertionsList<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError = RpcStatus>(
 params: undefined |  DirectoryAssertionV3AssertionsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryAssertionV3AssertionsList<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError = RpcStatus>(
 params?: DirectoryAssertionV3AssertionsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryAssertionV3AssertionsList<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError = RpcStatus>(
 params?: DirectoryAssertionV3AssertionsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List assertions
 */

export function useDirectoryAssertionV3AssertionsList<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError = RpcStatus>(
 params?: DirectoryAssertionV3AssertionsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryAssertionV3AssertionsListHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useDirectoryAssertionV3AssertionsListQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns check outcome.
 * @summary Check
 */
export const useDirectoryReaderV3CheckHook = () => {
        const directoryReaderV3Check = useDirectoryReaderClient<V3CheckResponse>();

        return useCallback((
    v3CheckRequest: V3CheckRequest,
 signal?: AbortSignal
) => {
        return directoryReaderV3Check(
          {url: `/api/v3/directory/check`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: v3CheckRequest, signal
    },
          );
        }, [directoryReaderV3Check])
      }
    


export const useDirectoryReaderV3CheckMutationOptions = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckHook>>>, TError,{data: V3CheckRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckHook>>>, TError,{data: V3CheckRequest}, TContext> => {
    
const mutationKey = ['directoryReaderV3Check'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const directoryReaderV3Check =  useDirectoryReaderV3CheckHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckHook>>>, {data: V3CheckRequest}> = (props) => {
          const {data} = props ?? {};

          return  directoryReaderV3Check(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DirectoryReaderV3CheckMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckHook>>>>
    export type DirectoryReaderV3CheckMutationBody = V3CheckRequest
    export type DirectoryReaderV3CheckMutationError = RpcStatus

    /**
 * @summary Check
 */
export const useDirectoryReaderV3Check = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckHook>>>, TError,{data: V3CheckRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckHook>>>,
        TError,
        {data: V3CheckRequest},
        TContext
      > => {

      const mutationOptions = useDirectoryReaderV3CheckMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Returns check permission outcome.
 * @summary Check permission
 */
export const useDirectoryReaderV3CheckPermissionHook = () => {
        const directoryReaderV3CheckPermission = useDirectoryReaderClient<V3CheckPermissionResponse>();

        return useCallback((
    v3CheckPermissionRequest: V3CheckPermissionRequest,
 signal?: AbortSignal
) => {
        return directoryReaderV3CheckPermission(
          {url: `/api/v3/directory/check/permission`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: v3CheckPermissionRequest, signal
    },
          );
        }, [directoryReaderV3CheckPermission])
      }
    


export const useDirectoryReaderV3CheckPermissionMutationOptions = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckPermissionHook>>>, TError,{data: V3CheckPermissionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckPermissionHook>>>, TError,{data: V3CheckPermissionRequest}, TContext> => {
    
const mutationKey = ['directoryReaderV3CheckPermission'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const directoryReaderV3CheckPermission =  useDirectoryReaderV3CheckPermissionHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckPermissionHook>>>, {data: V3CheckPermissionRequest}> = (props) => {
          const {data} = props ?? {};

          return  directoryReaderV3CheckPermission(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DirectoryReaderV3CheckPermissionMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckPermissionHook>>>>
    export type DirectoryReaderV3CheckPermissionMutationBody = V3CheckPermissionRequest
    export type DirectoryReaderV3CheckPermissionMutationError = RpcStatus

    /**
 * @summary Check permission
 */
export const useDirectoryReaderV3CheckPermission = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckPermissionHook>>>, TError,{data: V3CheckPermissionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckPermissionHook>>>,
        TError,
        {data: V3CheckPermissionRequest},
        TContext
      > => {

      const mutationOptions = useDirectoryReaderV3CheckPermissionMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Returns check relation outcome.
 * @summary Check relation
 */
export const useDirectoryReaderV3CheckRelationHook = () => {
        const directoryReaderV3CheckRelation = useDirectoryReaderClient<V3CheckRelationResponse>();

        return useCallback((
    v3CheckRelationRequest: V3CheckRelationRequest,
 signal?: AbortSignal
) => {
        return directoryReaderV3CheckRelation(
          {url: `/api/v3/directory/check/relation`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: v3CheckRelationRequest, signal
    },
          );
        }, [directoryReaderV3CheckRelation])
      }
    


export const useDirectoryReaderV3CheckRelationMutationOptions = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckRelationHook>>>, TError,{data: V3CheckRelationRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckRelationHook>>>, TError,{data: V3CheckRelationRequest}, TContext> => {
    
const mutationKey = ['directoryReaderV3CheckRelation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const directoryReaderV3CheckRelation =  useDirectoryReaderV3CheckRelationHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckRelationHook>>>, {data: V3CheckRelationRequest}> = (props) => {
          const {data} = props ?? {};

          return  directoryReaderV3CheckRelation(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DirectoryReaderV3CheckRelationMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckRelationHook>>>>
    export type DirectoryReaderV3CheckRelationMutationBody = V3CheckRelationRequest
    export type DirectoryReaderV3CheckRelationMutationError = RpcStatus

    /**
 * @summary Check relation
 */
export const useDirectoryReaderV3CheckRelation = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckRelationHook>>>, TError,{data: V3CheckRelationRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3CheckRelationHook>>>,
        TError,
        {data: V3CheckRelationRequest},
        TContext
      > => {

      const mutationOptions = useDirectoryReaderV3CheckRelationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Returns multiple check outcomes.
 * @summary Checks
 */
export const useDirectoryReaderV3ChecksHook = () => {
        const directoryReaderV3Checks = useDirectoryReaderClient<V3ChecksResponse>();

        return useCallback((
    v3ChecksRequest: V3ChecksRequest,
 signal?: AbortSignal
) => {
        return directoryReaderV3Checks(
          {url: `/api/v3/directory/checks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: v3ChecksRequest, signal
    },
          );
        }, [directoryReaderV3Checks])
      }
    


export const useDirectoryReaderV3ChecksMutationOptions = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ChecksHook>>>, TError,{data: V3ChecksRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ChecksHook>>>, TError,{data: V3ChecksRequest}, TContext> => {
    
const mutationKey = ['directoryReaderV3Checks'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const directoryReaderV3Checks =  useDirectoryReaderV3ChecksHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ChecksHook>>>, {data: V3ChecksRequest}> = (props) => {
          const {data} = props ?? {};

          return  directoryReaderV3Checks(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DirectoryReaderV3ChecksMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ChecksHook>>>>
    export type DirectoryReaderV3ChecksMutationBody = V3ChecksRequest
    export type DirectoryReaderV3ChecksMutationError = RpcStatus

    /**
 * @summary Checks
 */
export const useDirectoryReaderV3Checks = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ChecksHook>>>, TError,{data: V3ChecksRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ChecksHook>>>,
        TError,
        {data: V3ChecksRequest},
        TContext
      > => {

      const mutationOptions = useDirectoryReaderV3ChecksMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Returns object graph from anchor to subject or object.
 * @summary Get graph
 */
export const useDirectoryReaderV3GraphHook = () => {
        const directoryReaderV3Graph = useDirectoryReaderClient<V3GetGraphResponse>();

        return useCallback((
    objectType: string,
    relation: string,
    subjectType: string,
    params?: DirectoryReaderV3GraphParams,
 signal?: AbortSignal
) => {
        return directoryReaderV3Graph(
          {url: `/api/v3/directory/graph/${objectType}/${relation}/${subjectType}`, method: 'GET',
        params, signal
    },
          );
        }, [directoryReaderV3Graph])
      }
    

export const getDirectoryReaderV3GraphQueryKey = (objectType: string,
    relation: string,
    subjectType: string,
    params?: DirectoryReaderV3GraphParams,) => {
    return [`/api/v3/directory/graph/${objectType}/${relation}/${subjectType}`, ...(params ? [params]: [])] as const;
    }

    
export const useDirectoryReaderV3GraphQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>, TError = RpcStatus>(objectType: string,
    relation: string,
    subjectType: string,
    params?: DirectoryReaderV3GraphParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDirectoryReaderV3GraphQueryKey(objectType,relation,subjectType,params);

  const directoryReaderV3Graph =  useDirectoryReaderV3GraphHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>> = ({ signal }) => directoryReaderV3Graph(objectType,relation,subjectType,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(objectType && relation && subjectType), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DirectoryReaderV3GraphQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>>
export type DirectoryReaderV3GraphQueryError = RpcStatus


export function useDirectoryReaderV3Graph<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>, TError = RpcStatus>(
 objectType: string,
    relation: string,
    subjectType: string,
    params: undefined |  DirectoryReaderV3GraphParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3Graph<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>, TError = RpcStatus>(
 objectType: string,
    relation: string,
    subjectType: string,
    params?: DirectoryReaderV3GraphParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3Graph<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>, TError = RpcStatus>(
 objectType: string,
    relation: string,
    subjectType: string,
    params?: DirectoryReaderV3GraphParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get graph
 */

export function useDirectoryReaderV3Graph<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>, TError = RpcStatus>(
 objectType: string,
    relation: string,
    subjectType: string,
    params?: DirectoryReaderV3GraphParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3GraphHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useDirectoryReaderV3GraphQueryOptions(objectType,relation,subjectType,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Delete manifest.
 * @summary Delete manifest
 */
export const useDirectoryModelV3ManifestDeleteHook = () => {
        const directoryModelV3ManifestDelete = useDirectoryModelClient<V3DeleteManifestResponse>();

        return useCallback((
    params?: DirectoryModelV3ManifestDeleteParams,
 ) => {
        return directoryModelV3ManifestDelete(
          {url: `/api/v3/directory/manifest`, method: 'DELETE',
        params
    },
          );
        }, [directoryModelV3ManifestDelete])
      }
    


export const useDirectoryModelV3ManifestDeleteMutationOptions = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryModelV3ManifestDeleteHook>>>, TError,{params?: DirectoryModelV3ManifestDeleteParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryModelV3ManifestDeleteHook>>>, TError,{params?: DirectoryModelV3ManifestDeleteParams}, TContext> => {
    
const mutationKey = ['directoryModelV3ManifestDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const directoryModelV3ManifestDelete =  useDirectoryModelV3ManifestDeleteHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryModelV3ManifestDeleteHook>>>, {params?: DirectoryModelV3ManifestDeleteParams}> = (props) => {
          const {params} = props ?? {};

          return  directoryModelV3ManifestDelete(params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DirectoryModelV3ManifestDeleteMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryModelV3ManifestDeleteHook>>>>
    
    export type DirectoryModelV3ManifestDeleteMutationError = RpcStatus

    /**
 * @summary Delete manifest
 */
export const useDirectoryModelV3ManifestDelete = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryModelV3ManifestDeleteHook>>>, TError,{params?: DirectoryModelV3ManifestDeleteParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDirectoryModelV3ManifestDeleteHook>>>,
        TError,
        {params?: DirectoryModelV3ManifestDeleteParams},
        TContext
      > => {

      const mutationOptions = useDirectoryModelV3ManifestDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Get manifest.
 * @summary Get manifest
 */
export const useDirectoryV3ManifestGetHook = () => {
        const directoryV3ManifestGet = useDirectoryModelClient<Blob>();

        return useCallback((
    
 signal?: AbortSignal
) => {
        return directoryV3ManifestGet(
          {url: `/api/v3/directory/manifest`, method: 'GET',
        responseType: 'blob', signal
    },
          );
        }, [directoryV3ManifestGet])
      }
    

export const getDirectoryV3ManifestGetQueryKey = () => {
    return [`/api/v3/directory/manifest`] as const;
    }

    
export const useDirectoryV3ManifestGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>, TError = void | RpcStatus>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDirectoryV3ManifestGetQueryKey();

  const directoryV3ManifestGet =  useDirectoryV3ManifestGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>> = ({ signal }) => directoryV3ManifestGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DirectoryV3ManifestGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>>
export type DirectoryV3ManifestGetQueryError = void | RpcStatus


export function useDirectoryV3ManifestGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>, TError = void | RpcStatus>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryV3ManifestGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>, TError = void | RpcStatus>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryV3ManifestGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>, TError = void | RpcStatus>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get manifest
 */

export function useDirectoryV3ManifestGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>, TError = void | RpcStatus>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useDirectoryV3ManifestGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get manifest metadata.
 * @summary Get manifest metadata
 */
export const useDirectoryV3ManifestGetMetadataHook = () => {
        const directoryV3ManifestGetMetadata = useDirectoryReaderClient<void>();

        return useCallback((
    
 signal?: AbortSignal
) => {
        return directoryV3ManifestGetMetadata(
          {url: `/api/v3/directory/manifest`, method: 'HEAD', signal
    },
          );
        }, [directoryV3ManifestGetMetadata])
      }
    


export const useDirectoryV3ManifestGetMetadataMutationOptions = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetMetadataHook>>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetMetadataHook>>>, TError,void, TContext> => {
    
const mutationKey = ['directoryV3ManifestGetMetadata'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const directoryV3ManifestGetMetadata =  useDirectoryV3ManifestGetMetadataHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetMetadataHook>>>, void> = () => {
          

          return  directoryV3ManifestGetMetadata()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DirectoryV3ManifestGetMetadataMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetMetadataHook>>>>
    
    export type DirectoryV3ManifestGetMetadataMutationError = RpcStatus

    /**
 * @summary Get manifest metadata
 */
export const useDirectoryV3ManifestGetMetadata = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetMetadataHook>>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestGetMetadataHook>>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = useDirectoryV3ManifestGetMetadataMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Set manifest.
 * @summary Set manifest
 */
export const useDirectoryV3ManifestSetHook = () => {
        const directoryV3ManifestSet = useDirectoryModelClient<V3SetManifestResponse>();

        return useCallback((
    directoryV3ManifestSetBody: Blob,
 signal?: AbortSignal
) => {
        return directoryV3ManifestSet(
          {url: `/api/v3/directory/manifest`, method: 'POST',
      headers: {'Content-Type': 'application/yaml', },
      data: directoryV3ManifestSetBody, signal
    },
          );
        }, [directoryV3ManifestSet])
      }
    


export const useDirectoryV3ManifestSetMutationOptions = <TError = void | RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestSetHook>>>, TError,{data: Blob}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestSetHook>>>, TError,{data: Blob}, TContext> => {
    
const mutationKey = ['directoryV3ManifestSet'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const directoryV3ManifestSet =  useDirectoryV3ManifestSetHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestSetHook>>>, {data: Blob}> = (props) => {
          const {data} = props ?? {};

          return  directoryV3ManifestSet(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DirectoryV3ManifestSetMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestSetHook>>>>
    export type DirectoryV3ManifestSetMutationBody = Blob
    export type DirectoryV3ManifestSetMutationError = void | RpcStatus

    /**
 * @summary Set manifest
 */
export const useDirectoryV3ManifestSet = <TError = void | RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestSetHook>>>, TError,{data: Blob}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDirectoryV3ManifestSetHook>>>,
        TError,
        {data: Blob},
        TContext
      > => {

      const mutationOptions = useDirectoryV3ManifestSetMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Set object.
 * @summary Set object
 */
export const useDirectoryWriterV3ObjectSetHook = () => {
        const directoryWriterV3ObjectSet = useDirectoryWriterClient<V3SetObjectResponse>();

        return useCallback((
    v3SetObjectRequest: V3SetObjectRequest,
 signal?: AbortSignal
) => {
        return directoryWriterV3ObjectSet(
          {url: `/api/v3/directory/object`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: v3SetObjectRequest, signal
    },
          );
        }, [directoryWriterV3ObjectSet])
      }
    


export const useDirectoryWriterV3ObjectSetMutationOptions = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3ObjectSetHook>>>, TError,{data: V3SetObjectRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3ObjectSetHook>>>, TError,{data: V3SetObjectRequest}, TContext> => {
    
const mutationKey = ['directoryWriterV3ObjectSet'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const directoryWriterV3ObjectSet =  useDirectoryWriterV3ObjectSetHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3ObjectSetHook>>>, {data: V3SetObjectRequest}> = (props) => {
          const {data} = props ?? {};

          return  directoryWriterV3ObjectSet(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DirectoryWriterV3ObjectSetMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3ObjectSetHook>>>>
    export type DirectoryWriterV3ObjectSetMutationBody = V3SetObjectRequest
    export type DirectoryWriterV3ObjectSetMutationError = RpcStatus

    /**
 * @summary Set object
 */
export const useDirectoryWriterV3ObjectSet = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3ObjectSetHook>>>, TError,{data: V3SetObjectRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3ObjectSetHook>>>,
        TError,
        {data: V3SetObjectRequest},
        TContext
      > => {

      const mutationOptions = useDirectoryWriterV3ObjectSetMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Delete object.
 * @summary Delete object
 */
export const useDirectoryWriterV3ObjectDeleteHook = () => {
        const directoryWriterV3ObjectDelete = useDirectoryWriterClient<V3DeleteObjectResponse>();

        return useCallback((
    objectType: string,
    objectId: string,
    params?: DirectoryWriterV3ObjectDeleteParams,
 ) => {
        return directoryWriterV3ObjectDelete(
          {url: `/api/v3/directory/object/${objectType}/${objectId}`, method: 'DELETE',
        params
    },
          );
        }, [directoryWriterV3ObjectDelete])
      }
    


export const useDirectoryWriterV3ObjectDeleteMutationOptions = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3ObjectDeleteHook>>>, TError,{objectType: string;objectId: string;params?: DirectoryWriterV3ObjectDeleteParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3ObjectDeleteHook>>>, TError,{objectType: string;objectId: string;params?: DirectoryWriterV3ObjectDeleteParams}, TContext> => {
    
const mutationKey = ['directoryWriterV3ObjectDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const directoryWriterV3ObjectDelete =  useDirectoryWriterV3ObjectDeleteHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3ObjectDeleteHook>>>, {objectType: string;objectId: string;params?: DirectoryWriterV3ObjectDeleteParams}> = (props) => {
          const {objectType,objectId,params} = props ?? {};

          return  directoryWriterV3ObjectDelete(objectType,objectId,params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DirectoryWriterV3ObjectDeleteMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3ObjectDeleteHook>>>>
    
    export type DirectoryWriterV3ObjectDeleteMutationError = RpcStatus

    /**
 * @summary Delete object
 */
export const useDirectoryWriterV3ObjectDelete = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3ObjectDeleteHook>>>, TError,{objectType: string;objectId: string;params?: DirectoryWriterV3ObjectDeleteParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3ObjectDeleteHook>>>,
        TError,
        {objectType: string;objectId: string;params?: DirectoryWriterV3ObjectDeleteParams},
        TContext
      > => {

      const mutationOptions = useDirectoryWriterV3ObjectDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Returns single object instance, optionally with relations.
 * @summary Get object instance
 */
export const useDirectoryReaderV3ObjectGetHook = () => {
        const directoryReaderV3ObjectGet = useDirectoryReaderClient<V3GetObjectResponse>();

        return useCallback((
    objectType: string,
    objectId: string,
    params?: DirectoryReaderV3ObjectGetParams,
 signal?: AbortSignal
) => {
        return directoryReaderV3ObjectGet(
          {url: `/api/v3/directory/object/${objectType}/${objectId}`, method: 'GET',
        params, signal
    },
          );
        }, [directoryReaderV3ObjectGet])
      }
    

export const getDirectoryReaderV3ObjectGetQueryKey = (objectType: string,
    objectId: string,
    params?: DirectoryReaderV3ObjectGetParams,) => {
    return [`/api/v3/directory/object/${objectType}/${objectId}`, ...(params ? [params]: [])] as const;
    }

    
export const useDirectoryReaderV3ObjectGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>, TError = unknown | RpcStatus>(objectType: string,
    objectId: string,
    params?: DirectoryReaderV3ObjectGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDirectoryReaderV3ObjectGetQueryKey(objectType,objectId,params);

  const directoryReaderV3ObjectGet =  useDirectoryReaderV3ObjectGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>> = ({ signal }) => directoryReaderV3ObjectGet(objectType,objectId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(objectType && objectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DirectoryReaderV3ObjectGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>>
export type DirectoryReaderV3ObjectGetQueryError = unknown | RpcStatus


export function useDirectoryReaderV3ObjectGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>, TError = unknown | RpcStatus>(
 objectType: string,
    objectId: string,
    params: undefined |  DirectoryReaderV3ObjectGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3ObjectGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>, TError = unknown | RpcStatus>(
 objectType: string,
    objectId: string,
    params?: DirectoryReaderV3ObjectGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3ObjectGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>, TError = unknown | RpcStatus>(
 objectType: string,
    objectId: string,
    params?: DirectoryReaderV3ObjectGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get object instance
 */

export function useDirectoryReaderV3ObjectGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>, TError = unknown | RpcStatus>(
 objectType: string,
    objectId: string,
    params?: DirectoryReaderV3ObjectGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useDirectoryReaderV3ObjectGetQueryOptions(objectType,objectId,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns list of object instances.
 * @summary List object instances
 */
export const useDirectoryReaderV3ObjectsListHook = () => {
        const directoryReaderV3ObjectsList = useDirectoryReaderClient<V3GetObjectsResponse>();

        return useCallback((
    params?: DirectoryReaderV3ObjectsListParams,
 signal?: AbortSignal
) => {
        return directoryReaderV3ObjectsList(
          {url: `/api/v3/directory/objects`, method: 'GET',
        params, signal
    },
          );
        }, [directoryReaderV3ObjectsList])
      }
    

export const getDirectoryReaderV3ObjectsListQueryKey = (params?: DirectoryReaderV3ObjectsListParams,) => {
    return [`/api/v3/directory/objects`, ...(params ? [params]: [])] as const;
    }

    
export const useDirectoryReaderV3ObjectsListInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, DirectoryReaderV3ObjectsListParams['page.token']>, TError = RpcStatus>(params?: DirectoryReaderV3ObjectsListParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, QueryKey, DirectoryReaderV3ObjectsListParams['page.token']>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDirectoryReaderV3ObjectsListQueryKey(params);

  const directoryReaderV3ObjectsList =  useDirectoryReaderV3ObjectsListHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, QueryKey, DirectoryReaderV3ObjectsListParams['page.token']> = ({ signal, pageParam }) => directoryReaderV3ObjectsList({...params, 'page.token': pageParam || params?.['page.token']}, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, QueryKey, DirectoryReaderV3ObjectsListParams['page.token']> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DirectoryReaderV3ObjectsListInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>>
export type DirectoryReaderV3ObjectsListInfiniteQueryError = RpcStatus


export function useDirectoryReaderV3ObjectsListInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, DirectoryReaderV3ObjectsListParams['page.token']>, TError = RpcStatus>(
 params: undefined |  DirectoryReaderV3ObjectsListParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, QueryKey, DirectoryReaderV3ObjectsListParams['page.token']>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, QueryKey
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3ObjectsListInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, DirectoryReaderV3ObjectsListParams['page.token']>, TError = RpcStatus>(
 params?: DirectoryReaderV3ObjectsListParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, QueryKey, DirectoryReaderV3ObjectsListParams['page.token']>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, QueryKey
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3ObjectsListInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, DirectoryReaderV3ObjectsListParams['page.token']>, TError = RpcStatus>(
 params?: DirectoryReaderV3ObjectsListParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, QueryKey, DirectoryReaderV3ObjectsListParams['page.token']>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List object instances
 */

export function useDirectoryReaderV3ObjectsListInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, DirectoryReaderV3ObjectsListParams['page.token']>, TError = RpcStatus>(
 params?: DirectoryReaderV3ObjectsListParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, QueryKey, DirectoryReaderV3ObjectsListParams['page.token']>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useDirectoryReaderV3ObjectsListInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions , queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const useDirectoryReaderV3ObjectsListQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError = RpcStatus>(params?: DirectoryReaderV3ObjectsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDirectoryReaderV3ObjectsListQueryKey(params);

  const directoryReaderV3ObjectsList =  useDirectoryReaderV3ObjectsListHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>> = ({ signal }) => directoryReaderV3ObjectsList(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DirectoryReaderV3ObjectsListQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>>
export type DirectoryReaderV3ObjectsListQueryError = RpcStatus


export function useDirectoryReaderV3ObjectsList<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError = RpcStatus>(
 params: undefined |  DirectoryReaderV3ObjectsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3ObjectsList<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError = RpcStatus>(
 params?: DirectoryReaderV3ObjectsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3ObjectsList<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError = RpcStatus>(
 params?: DirectoryReaderV3ObjectsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List object instances
 */

export function useDirectoryReaderV3ObjectsList<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError = RpcStatus>(
 params?: DirectoryReaderV3ObjectsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3ObjectsListHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useDirectoryReaderV3ObjectsListQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Delete relation.
 * @summary Delete relation
 */
export const useDirectoryWriterV3RelationDeleteHook = () => {
        const directoryWriterV3RelationDelete = useDirectoryWriterClient<V3DeleteRelationResponse>();

        return useCallback((
    params: DirectoryWriterV3RelationDeleteParams,
 ) => {
        return directoryWriterV3RelationDelete(
          {url: `/api/v3/directory/relation`, method: 'DELETE',
        params
    },
          );
        }, [directoryWriterV3RelationDelete])
      }
    


export const useDirectoryWriterV3RelationDeleteMutationOptions = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3RelationDeleteHook>>>, TError,{params: DirectoryWriterV3RelationDeleteParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3RelationDeleteHook>>>, TError,{params: DirectoryWriterV3RelationDeleteParams}, TContext> => {
    
const mutationKey = ['directoryWriterV3RelationDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const directoryWriterV3RelationDelete =  useDirectoryWriterV3RelationDeleteHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3RelationDeleteHook>>>, {params: DirectoryWriterV3RelationDeleteParams}> = (props) => {
          const {params} = props ?? {};

          return  directoryWriterV3RelationDelete(params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DirectoryWriterV3RelationDeleteMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3RelationDeleteHook>>>>
    
    export type DirectoryWriterV3RelationDeleteMutationError = RpcStatus

    /**
 * @summary Delete relation
 */
export const useDirectoryWriterV3RelationDelete = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3RelationDeleteHook>>>, TError,{params: DirectoryWriterV3RelationDeleteParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3RelationDeleteHook>>>,
        TError,
        {params: DirectoryWriterV3RelationDeleteParams},
        TContext
      > => {

      const mutationOptions = useDirectoryWriterV3RelationDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Returns single relation instance, optionally with objects.
 * @summary Get relation instance
 */
export const useDirectoryReaderV3RelationGetHook = () => {
        const directoryReaderV3RelationGet = useDirectoryReaderClient<V3GetRelationResponse>();

        return useCallback((
    params: DirectoryReaderV3RelationGetParams,
 signal?: AbortSignal
) => {
        return directoryReaderV3RelationGet(
          {url: `/api/v3/directory/relation`, method: 'GET',
        params, signal
    },
          );
        }, [directoryReaderV3RelationGet])
      }
    

export const getDirectoryReaderV3RelationGetQueryKey = (params: DirectoryReaderV3RelationGetParams,) => {
    return [`/api/v3/directory/relation`, ...(params ? [params]: [])] as const;
    }

    
export const useDirectoryReaderV3RelationGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>, TError = unknown | RpcStatus>(params: DirectoryReaderV3RelationGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDirectoryReaderV3RelationGetQueryKey(params);

  const directoryReaderV3RelationGet =  useDirectoryReaderV3RelationGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>> = ({ signal }) => directoryReaderV3RelationGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DirectoryReaderV3RelationGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>>
export type DirectoryReaderV3RelationGetQueryError = unknown | RpcStatus


export function useDirectoryReaderV3RelationGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>, TError = unknown | RpcStatus>(
 params: DirectoryReaderV3RelationGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3RelationGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>, TError = unknown | RpcStatus>(
 params: DirectoryReaderV3RelationGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3RelationGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>, TError = unknown | RpcStatus>(
 params: DirectoryReaderV3RelationGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get relation instance
 */

export function useDirectoryReaderV3RelationGet<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>, TError = unknown | RpcStatus>(
 params: DirectoryReaderV3RelationGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useDirectoryReaderV3RelationGetQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Set relation.
 * @summary Set relation
 */
export const useDirectoryWriterV3RelationSetHook = () => {
        const directoryWriterV3RelationSet = useDirectoryWriterClient<V3SetRelationResponse>();

        return useCallback((
    v3SetRelationRequest: V3SetRelationRequest,
 signal?: AbortSignal
) => {
        return directoryWriterV3RelationSet(
          {url: `/api/v3/directory/relation`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: v3SetRelationRequest, signal
    },
          );
        }, [directoryWriterV3RelationSet])
      }
    


export const useDirectoryWriterV3RelationSetMutationOptions = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3RelationSetHook>>>, TError,{data: V3SetRelationRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3RelationSetHook>>>, TError,{data: V3SetRelationRequest}, TContext> => {
    
const mutationKey = ['directoryWriterV3RelationSet'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const directoryWriterV3RelationSet =  useDirectoryWriterV3RelationSetHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3RelationSetHook>>>, {data: V3SetRelationRequest}> = (props) => {
          const {data} = props ?? {};

          return  directoryWriterV3RelationSet(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DirectoryWriterV3RelationSetMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3RelationSetHook>>>>
    export type DirectoryWriterV3RelationSetMutationBody = V3SetRelationRequest
    export type DirectoryWriterV3RelationSetMutationError = RpcStatus

    /**
 * @summary Set relation
 */
export const useDirectoryWriterV3RelationSet = <TError = RpcStatus,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3RelationSetHook>>>, TError,{data: V3SetRelationRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDirectoryWriterV3RelationSetHook>>>,
        TError,
        {data: V3SetRelationRequest},
        TContext
      > => {

      const mutationOptions = useDirectoryWriterV3RelationSetMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Returns list of relation instances.
 * @summary List relations instances
 */
export const useDirectoryReaderV3RelationsListHook = () => {
        const directoryReaderV3RelationsList = useDirectoryReaderClient<V3GetRelationsResponse>();

        return useCallback((
    params?: DirectoryReaderV3RelationsListParams,
 signal?: AbortSignal
) => {
        return directoryReaderV3RelationsList(
          {url: `/api/v3/directory/relations`, method: 'GET',
        params, signal
    },
          );
        }, [directoryReaderV3RelationsList])
      }
    

export const getDirectoryReaderV3RelationsListQueryKey = (params?: DirectoryReaderV3RelationsListParams,) => {
    return [`/api/v3/directory/relations`, ...(params ? [params]: [])] as const;
    }

    
export const useDirectoryReaderV3RelationsListInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, DirectoryReaderV3RelationsListParams['page.token']>, TError = RpcStatus>(params?: DirectoryReaderV3RelationsListParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, QueryKey, DirectoryReaderV3RelationsListParams['page.token']>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDirectoryReaderV3RelationsListQueryKey(params);

  const directoryReaderV3RelationsList =  useDirectoryReaderV3RelationsListHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, QueryKey, DirectoryReaderV3RelationsListParams['page.token']> = ({ signal, pageParam }) => directoryReaderV3RelationsList({...params, 'page.token': pageParam || params?.['page.token']}, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, QueryKey, DirectoryReaderV3RelationsListParams['page.token']> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DirectoryReaderV3RelationsListInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>>
export type DirectoryReaderV3RelationsListInfiniteQueryError = RpcStatus


export function useDirectoryReaderV3RelationsListInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, DirectoryReaderV3RelationsListParams['page.token']>, TError = RpcStatus>(
 params: undefined |  DirectoryReaderV3RelationsListParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, QueryKey, DirectoryReaderV3RelationsListParams['page.token']>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, QueryKey
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3RelationsListInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, DirectoryReaderV3RelationsListParams['page.token']>, TError = RpcStatus>(
 params?: DirectoryReaderV3RelationsListParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, QueryKey, DirectoryReaderV3RelationsListParams['page.token']>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, QueryKey
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3RelationsListInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, DirectoryReaderV3RelationsListParams['page.token']>, TError = RpcStatus>(
 params?: DirectoryReaderV3RelationsListParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, QueryKey, DirectoryReaderV3RelationsListParams['page.token']>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List relations instances
 */

export function useDirectoryReaderV3RelationsListInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, DirectoryReaderV3RelationsListParams['page.token']>, TError = RpcStatus>(
 params?: DirectoryReaderV3RelationsListParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError, TData, Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, QueryKey, DirectoryReaderV3RelationsListParams['page.token']>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useDirectoryReaderV3RelationsListInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions , queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const useDirectoryReaderV3RelationsListQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError = RpcStatus>(params?: DirectoryReaderV3RelationsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDirectoryReaderV3RelationsListQueryKey(params);

  const directoryReaderV3RelationsList =  useDirectoryReaderV3RelationsListHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>> = ({ signal }) => directoryReaderV3RelationsList(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DirectoryReaderV3RelationsListQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>>
export type DirectoryReaderV3RelationsListQueryError = RpcStatus


export function useDirectoryReaderV3RelationsList<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError = RpcStatus>(
 params: undefined |  DirectoryReaderV3RelationsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3RelationsList<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError = RpcStatus>(
 params?: DirectoryReaderV3RelationsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirectoryReaderV3RelationsList<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError = RpcStatus>(
 params?: DirectoryReaderV3RelationsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List relations instances
 */

export function useDirectoryReaderV3RelationsList<TData = Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError = RpcStatus>(
 params?: DirectoryReaderV3RelationsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useDirectoryReaderV3RelationsListHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useDirectoryReaderV3RelationsListQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
