/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */

/**
 * Identity types, describes the payload type of the identity field inside the IdentityContext message.

 - IDENTITY_TYPE_UNKNOWN: Unknown, value not set, requests will fail with identity type not set error.
 - IDENTITY_TYPE_NONE: None, no explicit identity context set, equals anonymous.
 - IDENTITY_TYPE_SUB: Sub(ject), identity field contains an oAUTH subject.
 - IDENTITY_TYPE_JWT: JWT, identity field contains a JWT access token.
 - IDENTITY_TYPE_MANUAL: Manual, propagates thw identity field as-is, without validation, into the input object.
 */
export type ApiIdentityType = typeof ApiIdentityType[keyof typeof ApiIdentityType];


 
export const ApiIdentityType = {
  IDENTITY_TYPE_UNKNOWN: 'IDENTITY_TYPE_UNKNOWN',
  IDENTITY_TYPE_NONE: 'IDENTITY_TYPE_NONE',
  IDENTITY_TYPE_SUB: 'IDENTITY_TYPE_SUB',
  IDENTITY_TYPE_JWT: 'IDENTITY_TYPE_JWT',
  IDENTITY_TYPE_MANUAL: 'IDENTITY_TYPE_MANUAL',
} as const;
