/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */
import type { ApiIdentityType } from './apiIdentityType';

export interface ApiIdentityContext {
  identity?: string;
  type?: ApiIdentityType;
}
