/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */

export interface ApiModule {
  ast?: unknown;
  id?: string;
  package_path?: string;
  package_root?: string;
  raw?: string;
}
