/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */

export type PoliciesGetParams = {
field_mask?: string;
/**
 * label identifying the instance of the policy
 */
'policy_instance.instance_label'?: string;
/**
 * policy name
 */
'policy_instance.name'?: string;
};
