/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */

export interface ProtobufAny {
  '@type'?: string;
  [key: string]: unknown;
}
