/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */
import type { ProtobufAny } from './protobufAny';

export interface RpcStatus {
  code?: number;
  details?: ProtobufAny[];
  message?: string;
}
