/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */
import type { ApiIdentityContext } from './apiIdentityContext';
import type { ApiPolicyContext } from './apiPolicyContext';
import type { ApiPolicyInstance } from './apiPolicyInstance';
import type { V2CompileRequestResourceContext } from './v2CompileRequestResourceContext';
import type { V2QueryOptions } from './v2QueryOptions';

export interface V2CompileRequest {
  disable_inlining?: string[];
  identity_context?: ApiIdentityContext;
  input?: string;
  options?: V2QueryOptions;
  policy_context?: ApiPolicyContext;
  policy_instance?: ApiPolicyInstance;
  query?: string;
  resource_context?: V2CompileRequestResourceContext;
  unknowns?: string[];
}
