/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */
import type { V2CompileResponseMetrics } from './v2CompileResponseMetrics';
import type { V2CompileResponseResult } from './v2CompileResponseResult';
import type { V2CompileResponseTraceItem } from './v2CompileResponseTraceItem';

export interface V2CompileResponse {
  metrics?: V2CompileResponseMetrics;
  result?: V2CompileResponseResult;
  trace?: V2CompileResponseTraceItem[];
  trace_summary?: string[];
}
