/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */
import type { ApiIdentityContext } from './apiIdentityContext';
import type { V2DecisionTreeOptions } from './v2DecisionTreeOptions';
import type { ApiPolicyContext } from './apiPolicyContext';
import type { ApiPolicyInstance } from './apiPolicyInstance';
import type { V2DecisionTreeRequestResourceContext } from './v2DecisionTreeRequestResourceContext';

export interface V2DecisionTreeRequest {
  identity_context?: ApiIdentityContext;
  options?: V2DecisionTreeOptions;
  policy_context?: ApiPolicyContext;
  policy_instance?: ApiPolicyInstance;
  resource_context?: V2DecisionTreeRequestResourceContext;
}
