/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */
import type { V2PathSeparator } from './v2PathSeparator';

export interface V2DecisionTreeOptions {
  path_separator?: V2PathSeparator;
}
