/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */
import type { Authorizerv2Decision } from './authorizerv2Decision';

export interface V2IsResponse {
  decisions?: Authorizerv2Decision[];
}
