/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */

export type V2PathSeparator = typeof V2PathSeparator[keyof typeof V2PathSeparator];


 
export const V2PathSeparator = {
  PATH_SEPARATOR_UNKNOWN: 'PATH_SEPARATOR_UNKNOWN',
  PATH_SEPARATOR_DOT: 'PATH_SEPARATOR_DOT',
  PATH_SEPARATOR_SLASH: 'PATH_SEPARATOR_SLASH',
} as const;
