/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */
import type { ApiIdentityContext } from './apiIdentityContext';
import type { ApiPolicyContext } from './apiPolicyContext';
import type { ApiPolicyInstance } from './apiPolicyInstance';
import type { V2QueryOptions } from './v2QueryOptions';
import type { V2QueryRequestResourceContext } from './v2QueryRequestResourceContext';

export interface V2QueryRequest {
  identity_context?: ApiIdentityContext;
  input?: string;
  options?: V2QueryOptions;
  policy_context?: ApiPolicyContext;
  policy_instance?: ApiPolicyInstance;
  query?: string;
  resource_context?: V2QueryRequestResourceContext;
}
