/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */
import type { V2TraceLevel } from './v2TraceLevel';

export interface V2QueryOptions {
  instrument?: boolean;
  metrics?: boolean;
  trace?: V2TraceLevel;
  trace_summary?: boolean;
}
