/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Authorizer
 * Authorizer service
 * OpenAPI spec version: v0.20.10
 */

export type V2TraceLevel = typeof V2TraceLevel[keyof typeof V2TraceLevel];


 
export const V2TraceLevel = {
  TRACE_LEVEL_UNKNOWN: 'TRACE_LEVEL_UNKNOWN',
  TRACE_LEVEL_OFF: 'TRACE_LEVEL_OFF',
  TRACE_LEVEL_FULL: 'TRACE_LEVEL_FULL',
  TRACE_LEVEL_NOTES: 'TRACE_LEVEL_NOTES',
  TRACE_LEVEL_FAILS: 'TRACE_LEVEL_FAILS',
} as const;
