/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */

export type DirectoryAssertionV3AssertionsListParams = {
/**
 * requested page size, valid value between 1-100 rows (default 100)
 */
'page.size'?: number;
/**
 * pagination start token, default ""
 */
'page.token'?: string;
};
