/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */

export type DirectoryReaderV3RelationGetParams = {
/**
 * object identifier
 */
object_id: string;
/**
 * object type
 */
object_type: string;
/**
 * relation name
 */
relation: string;
/**
 * subject identifier
 */
subject_id: string;
/**
 * optional subject relation name
 */
subject_relation?: string;
/**
 * subject type
 */
subject_type: string;
/**
 * materialize relation objects
 */
with_objects?: boolean;
};
