/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */

export type DirectoryReaderV3RelationsListParams = {
/**
 * object identifier
 */
object_id?: string;
/**
 * object type
 */
object_type?: string;
/**
 * requested page size, valid value between 1-100 rows (default 100)
 */
'page.size'?: number;
/**
 * pagination start token, default ""
 */
'page.token'?: string;
/**
 * relation name
 */
relation?: string;
/**
 * subject identifier
 */
subject_id?: string;
/**
 * optional subject relation name
 */
subject_relation?: string;
/**
 * subject type
 */
subject_type?: string;
/**
 * only return relations that do not have a subject relation.
 */
with_empty_subject_relation?: boolean;
/**
 * materialize relation objects
 */
with_objects?: boolean;
};
