/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */

export type DirectoryReaderV3GraphParams = {
/**
 * object identifier
 */
object_id?: string;
/**
 * subject identifier
 */
subject_id?: string;
/**
 * subject relation
 */
subject_relation?: string;
/**
 * return graph paths for each result
 */
explain?: boolean;
/**
 * collect trace information
 */
trace?: boolean;
};
