/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */

export type DirectoryWriterV3ObjectDeleteParams = {
/**
 * delete object relations, both object and subject relations.
 */
with_relations?: boolean;
};
