/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */

/**
 * `NullValue` is a singleton enumeration to represent the null value for the
`Value` type union.

The JSON representation for `NullValue` is JSON `null`.

 - NULL_VALUE: Null value.
 */
export type ProtobufNullValue = typeof ProtobufNullValue[keyof typeof ProtobufNullValue];


 
export const ProtobufNullValue = {
  NULL_VALUE: 'NULL_VALUE',
} as const;
