/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */
import type { ProtobufAny } from './protobufAny';

export interface RpcStatus {
  code?: number;
  details?: ProtobufAny[];
  message?: string;
}
