import type { V1Action } from './v1Action';
/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V1Page } from './v1Page';

export interface V1ActionSearchResponse {
  page?: V1Page;
  results?: V1Action[];
}
