/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V1ActionProperties } from './v1ActionProperties';

export interface V1Action {
  name?: string;
  properties?: V1ActionProperties;
}
