/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V1Action } from './v1Action';
import type { V1EvaluationRequestContext } from './v1EvaluationRequestContext';
import type { V1Resource } from './v1Resource';
import type { V1Subject } from './v1Subject';

export interface V1EvaluationRequest {
  action?: V1Action;
  context?: V1EvaluationRequestContext;
  resource?: V1Resource;
  subject?: V1Subject;
}
