/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V1EvaluationResponse } from './v1EvaluationResponse';

export interface V1EvaluationsResponse {
  decisions?: V1EvaluationResponse[];
}
