/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V1Action } from './v1Action';
import type { V1EvaluationsRequestContext } from './v1EvaluationsRequestContext';
import type { V1EvaluationRequest } from './v1EvaluationRequest';
import type { V1EvaluationsRequestOptions } from './v1EvaluationsRequestOptions';
import type { V1Resource } from './v1Resource';
import type { V1Subject } from './v1Subject';

export interface V1EvaluationsRequest {
  action?: V1Action;
  context?: V1EvaluationsRequestContext;
  evaluations?: V1EvaluationRequest[];
  options?: V1EvaluationsRequestOptions;
  resource?: V1Resource;
  subject?: V1Subject;
}
