/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V1EvaluationResponseContext } from './v1EvaluationResponseContext';

export interface V1EvaluationResponse {
  context?: V1EvaluationResponseContext;
  decision?: boolean;
}
