/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V1Action } from './v1Action';
import type { V1ResourceSearchRequestContext } from './v1ResourceSearchRequestContext';
import type { V1Page } from './v1Page';
import type { V1Resource } from './v1Resource';
import type { V1Subject } from './v1Subject';

export interface V1ResourceSearchRequest {
  action?: V1Action;
  context?: V1ResourceSearchRequestContext;
  page?: V1Page;
  resource?: V1Resource;
  subject?: V1Subject;
}
