/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V1ResourceProperties } from './v1ResourceProperties';

export interface V1Resource {
  id?: string;
  properties?: V1ResourceProperties;
  type?: string;
}
