/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V1SubjectProperties } from './v1SubjectProperties';

export interface V1Subject {
  id?: string;
  properties?: V1SubjectProperties;
  type?: string;
}
