/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V1Page } from './v1Page';
import type { V1Subject } from './v1Subject';

export interface V1SubjectSearchResponse {
  page?: V1Page;
  results?: V1Subject[];
}
