import type { V3CheckPermissionRequest } from './v3CheckPermissionRequest';
import type { V3CheckRelationRequest } from './v3CheckRelationRequest';
/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3CheckRequest } from './v3CheckRequest';

export interface V3Assert {
  check?: V3CheckRequest;
  check_permission?: V3CheckPermissionRequest;
  check_relation?: V3CheckRelationRequest;
  description?: string;
  expected: boolean;
  id?: number;
}
