/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3CheckResponseContext } from './v3CheckResponseContext';

export interface V3CheckResponse {
  check?: boolean;
  context?: V3CheckResponseContext;
  trace?: string[];
}
