/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3CheckRequest } from './v3CheckRequest';

export interface V3ChecksRequest {
  checks?: V3CheckRequest[];
  default?: V3CheckRequest;
}
