/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */
import type { V3CheckResponse } from './v3CheckResponse';

export interface V3ChecksResponse {
  checks?: V3CheckResponse[];
}
