/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */
import type { V3DeleteObjectResponseResult } from './v3DeleteObjectResponseResult';

export interface V3DeleteObjectResponse {
  result?: V3DeleteObjectResponseResult;
}
