/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */
import type { V3DeleteAssertionResponseResult } from './v3DeleteAssertionResponseResult';

export interface V3DeleteAssertionResponse {
  result?: V3DeleteAssertionResponseResult;
}
