/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */
import type { V3DeleteRelationResponseResult } from './v3DeleteRelationResponseResult';

export interface V3DeleteRelationResponse {
  result?: V3DeleteRelationResponseResult;
}
