/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3DeleteManifestResponseResult } from './v3DeleteManifestResponseResult';

export interface V3DeleteManifestResponse {
  result?: V3DeleteManifestResponseResult;
}
