import type { V3ExportResponseStats } from './v3ExportResponseStats';
/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3Object } from './v3Object';
import type { V3Relation } from './v3Relation';

export interface V3ExportResponse {
  object?: V3Object;
  relation?: V3Relation;
  stats?: V3ExportResponseStats;
}
