/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3Object } from './v3Object';

export type V3GetRelationResponseObjects = {[key: string]: V3Object};
