/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3Body } from './v3Body';
import type { V3GetManifestResponseModel } from './v3GetManifestResponseModel';
import type { V3Metadata } from './v3Metadata';

export interface V3GetManifestResponse {
  body?: V3Body;
  metadata?: V3Metadata;
  model?: V3GetManifestResponseModel;
}
