/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */
import type { V3Assert } from './v3Assert';

export interface V3GetAssertionResponse {
  result?: V3Assert;
}
