import type { V3Object } from './v3Object';
/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3PaginationResponse } from './v3PaginationResponse';
import type { V3Relation } from './v3Relation';

export interface V3GetObjectResponse {
  page?: V3PaginationResponse;
  relations?: V3Relation[];
  result?: V3Object;
}
