/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3PaginationResponse } from './v3PaginationResponse';
import type { V3Object } from './v3Object';

export interface V3GetObjectsResponse {
  page?: V3PaginationResponse;
  results?: V3Object[];
}
