/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3GetRelationsResponseObjects } from './v3GetRelationsResponseObjects';
import type { V3PaginationResponse } from './v3PaginationResponse';
import type { V3Relation } from './v3Relation';

export interface V3GetRelationsResponse {
  objects?: V3GetRelationsResponseObjects;
  page?: V3PaginationResponse;
  results?: V3Relation[];
}
