/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */
import type { V3GetRelationResponseObjects } from './v3GetRelationResponseObjects';
import type { V3Relation } from './v3Relation';

export interface V3GetRelationResponse {
  objects?: V3GetRelationResponseObjects;
  result?: V3Relation;
}
