/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */
import type { V3GetGraphResponseExplanation } from './v3GetGraphResponseExplanation';
import type { V3ObjectIdentifier } from './v3ObjectIdentifier';

export interface V3GetGraphResponse {
  explanation?: V3GetGraphResponseExplanation;
  results?: V3ObjectIdentifier[];
  trace?: string[];
}
