/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3Object } from './v3Object';
import type { V3Opcode } from './v3Opcode';
import type { V3Relation } from './v3Relation';

export interface V3ImportRequest {
  object?: V3Object;
  op_code?: V3Opcode;
  relation?: V3Relation;
}
