/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */
import type { V3ImportCounter } from './v3ImportCounter';
import type { V3ImportStatus } from './v3ImportStatus';

export interface V3ImportResponse {
  counter?: V3ImportCounter;
  object?: V3ImportCounter;
  relation?: V3ImportCounter;
  status?: V3ImportStatus;
}
