/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3ImportRequest } from './v3ImportRequest';

export interface V3ImportStatus {
  code?: number;
  msg?: string;
  req?: V3ImportRequest;
}
