/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */

export interface V3ImportCounter {
  delete?: string;
  error?: string;
  recv?: string;
  set?: string;
  type?: string;
}
