import type { V3Assert } from './v3Assert';
/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3PaginationResponse } from './v3PaginationResponse';

export interface V3ListAssertionsResponse {
  page?: V3PaginationResponse;
  results?: V3Assert[];
}
