/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */

export interface V3Metadata {
  etag?: string;
  readonly updated_at?: string;
}
