/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */

export interface V3ObjectIdentifier {
  object_id: string;
  object_type: string;
}
