/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */

export type V3Opcode = typeof V3Opcode[keyof typeof V3Opcode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const V3Opcode = {
  OPCODE_UNKNOWN: 'OPCODE_UNKNOWN',
  OPCODE_SET: 'OPCODE_SET',
  OPCODE_DELETE: 'OPCODE_DELETE',
  OPCODE_DELETE_WITH_RELATIONS: 'OPCODE_DELETE_WITH_RELATIONS',
} as const;
