/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.2
 */

export interface V3Relation {
  readonly created_at?: string;
  etag?: string;
  object_id: string;
  object_type: string;
  relation: string;
  subject_id: string;
  subject_relation?: string;
  subject_type: string;
  readonly updated_at?: string;
}
