/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3SetManifestResponseResult } from './v3SetManifestResponseResult';

export interface V3SetManifestResponse {
  result?: V3SetManifestResponseResult;
}
