/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Directory
 * Directory service
 * OpenAPI spec version: v0.33.5
 */
import type { V3Relation } from './v3Relation';

export interface V3SetRelationResponse {
  result?: V3Relation;
}
